---
- ConfigTypeName: 'single'
  Well: False
  IndexStrategy: 'single'
  IndexSets:
    IndexI7: [ 'IndexI7Name', 'IndexI7' ]

- ConfigTypeName: 'single_well'
  Well: True
  IndexStrategy: 'single'
  IndexSets:
    IndexI7: [ 'WellI7', 'IndexI7Name', 'IndexI7' ]

- ConfigTypeName: 'combinatorial_dual_indexes'
  Well: False
  IndexStrategy: 'cdi'
  IndexSets:
    IndexI7: [ 'IndexI7Name', 'IndexI7' ]
    IndexI5: [ 'IndexI5Name', 'IndexI5' ]

- ConfigTypeName: 'combinatorial_dual_indexes_well'
  Well: True
  IndexStrategy: 'cdi'
  IndexSets:
    IndexI7: [ 'WellI7', 'IndexI7Name', 'IndexI7' ]
    IndexI5: [ 'WellI5', 'IndexI5Name', 'IndexI5' ]

- ConfigTypeName: 'unique_dual_indexes'
  Well: False
  IndexStrategy: 'udi'
  IndexSets:
    IndexDual: [ 'IndexI7Name', 'IndexI7', 'IndexI5Name', 'IndexI5' ]

- ConfigTypeName: 'unique_dual_indexes_well'
  Well: True
  IndexStrategy: 'udi'
  IndexSets:
    IndexDual: [ 'WellDual', 'IndexI7Name', 'IndexI7', 'IndexI5Name', 'IndexI5' ]
