---

- name: 'single_fixed_well'
  type: 'fixed'
  well_field_count: 1
  index_strategy: 'single'
  index_set_fields:
    IndexI7: [ 'well', 'index_i7_name', 'index_i7' ]

- name: 'dual_fixed_well'
  type: 'fixed'
  well_field_count: 1
  index_strategy: 'dual'
  index_set_fields:
    IndexDual: [ 'well', 'index_i7_name', 'index_i7', 'index_i5_name', 'index_i5' ]

- name: 'dual_standard_well'
  type: 'standard'
  well_field_count: 2
  index_strategy: 'dual'
  index_set_fields:
    IndexI7: [ 'well', 'index_i7_name', 'index_i7' ]
    IndexI5: [ 'well_2', 'index_i5_name', 'index_i5' ]

- name: 'i7_standard_well'
  type: 'standard'
  well_field_count: 1
  index_strategy: 'single'
  index_set_fields:
    IndexI7: [ 'well', 'index_i7_name', 'index_i7' ]

- name: 'dual_standard'
  type: 'standard'
  well_field_count: 0
  index_strategy: 'dual'
  index_set_fields:
    IndexI7: [ 'index_i7_name', 'index_i7' ]
    IndexI5: [ 'index_i5_name', 'index_i5' ]

- name: 'i7_standard'
  type: 'standard'
  well_field_count: 0
  index_strategy: 'dual'
  index_set_fields:
    IndexI7: [ 'index_i7_name', 'index_i7' ]
